/*
NOTE! This code is autogenerated.
Don't manually change this code.
Version [451fbde50057770bf5820107beeca0955a312969a0581e591c491e5d70e629bb]
*/
package dal

import (
    "context"    
    "database/sql"
    _ "embed"
    "errors"
    "strings"
    "sync/atomic"

    "fmt"
    "time"

    log "github.com/sirupsen/logrus"
    "github.com/patrickmn/go-cache"
    "github.com/sony/gobreaker"
)


type matchReactionCounterRepository struct {
    dbProvider          DBProvider
    cache               *cache.Cache  // Simple TTL cache for single items, for inmemory cache management
  	listCache           *cache.Cache // Cache for lists. Simple TTL cache, for inmemory cache management
    countCache          *cache.Cache // Cache for counts. Simple TTL cache, for inmemory cache management
    cacheProvider       CacheProvider
    configProvider      ConfigProvider
	dbBreaker           *gobreaker.CircuitBreaker
    telemetryProvider TelemetryProvider
    listEpoch         atomic.Int64
}

// NewMatchReactionCounterRepository now returns the MatchReactionCounterRepository interface.
func NewMatchReactionCounterRepository(
    provider DBProvider, 
    cacheProvider CacheProvider,
    configProvider ConfigProvider, 
    dbSettings gobreaker.Settings, 
    telemetry TelemetryProvider) MatchReactionCounterRepository {

    if configProvider == nil {
        configProvider = DefaultConfigProvider{}
    }

    if cacheProvider == nil {
        cacheProvider = NoopCacheProvider{}
    }

    if telemetry == nil {
		telemetry = NoopTelemetryProvider{}
	}

    if dbSettings.Name == "" {
        dbSettings.Name = "match_reaction_counter_dal"
    }
    if dbSettings.ReadyToTrip == nil {
        dbSettings.ReadyToTrip = func(counts gobreaker.Counts) bool {
            return counts.ConsecutiveFailures > 4
        }
    }
    if dbSettings.OnStateChange == nil {
		dbSettings.OnStateChange = OnCircuitBreakerStateChange
	}

    dbSettings.IsSuccessful = func(err error) bool {
		if err == nil {
			return true
		}
		// If the record just doesn't exist, the database is perfectly healthy
		if errors.Is(err, ErrNotFound) {
			return true
		}
		return false
	}


    if dbSettings.Timeout == 0 {
        dbSettings.Timeout = time.Second * 20
    }

    // Default expiration is 5 minutes and cleanup of 10 minutes
   	singleCache := cache.New(5*time.Minute, 10*time.Minute)
	listCache := cache.New(5*time.Minute, 10*time.Minute)
    countCache := cache.New(5*time.Minute, 10*time.Minute)

    

    newDAL := &matchReactionCounterRepository{
        dbProvider:     provider,
        cache:          singleCache,
        listCache:      listCache,
        countCache:     countCache,
        cacheProvider:  cacheProvider,
        configProvider: configProvider,
		dbBreaker:      gobreaker.NewCircuitBreaker(dbSettings),
        telemetryProvider: telemetry,
    }

    // Initialize the epoch and register the Pub/Sub handler
    newDAL.listEpoch.Store(time.Now().UnixNano())
    cacheProvider.OnBumpEpoch("match_reaction_counter", newDAL.onBumpEpoch)

    // initialize cache invalidation handler
    cacheProvider.OnCacheInvalidated("match_reaction_counter", newDAL.onCacheInvalidated)
    cacheProvider.OnCacheFlushList("match_reaction_counter", newDAL.onCacheFlushList)
    cacheProvider.OnCacheFlushItem("match_reaction_counter", newDAL.onCacheFlushItem)

    return newDAL
}

func (d *matchReactionCounterRepository) getCacheKey(id int64) string {
    return fmt.Sprintf("match_reaction_counter_id:%d", id)
}



func (d *matchReactionCounterRepository) getEpoch() int64 {
    return d.listEpoch.Load()
}

func (d *matchReactionCounterRepository) bumpEpoch() {
    d.listEpoch.Store(time.Now().UnixNano())
}

func (d *matchReactionCounterRepository) onBumpEpoch() {
    d.bumpEpoch()
}

func (d *matchReactionCounterRepository) InvalidateCache(entity *MatchReactionCounter) {
    cacheKey := d.getCacheKey(entity.ID)
	d.cache.Delete(cacheKey)

	// Invalidate cache entry across instances
	d.cacheProvider.InvalidateCache("match_reaction_counter", cacheKey)
}

func (d *matchReactionCounterRepository) FlushListCache() {
    // CACHING NOTE: listInvalidation is set to 'expire'. Global list caching ignored.
}

// FlushAllCache clears both list/count caches AND single-item caches locally, 
// and broadcasts the flush to other instances.
func (d *matchReactionCounterRepository) FlushAllCache() {
	d.cache.Flush()
	d.cacheProvider.FlushItemCache("match_reaction_counter")
}

// Handles cache_flush_item. Just clears the single items cache locally.
func (d *matchReactionCounterRepository) onCacheFlushItem() {
	d.cache.Flush()
}

// Handles cache invalidations. Just remove cached entry by key
func (d *matchReactionCounterRepository) onCacheInvalidated(key string) {
    d.cache.Delete(key)
}

// Handles cache_flush_list. Just clears all lists cache.
func (d *matchReactionCounterRepository) onCacheFlushList() {
}




//go:embed match_reaction_counter.sql
var schemaMatchReactionCounter string

func (d *matchReactionCounterRepository) CreateTable(ctx context.Context) error {
	// Get write database connection
	dbs := d.dbProvider.AllDatabases("matchReactionCounter", "write")

	for _, db := range dbs {
		// First check if table exists
		exists, err := d.tableExists(ctx, db)
		if err != nil {
			return fmt.Errorf("failed to check table existence: %w", err)
		}
		if exists {
		    log.Infof("CreateTable: table [%s] already exist", "match_reaction_counter")
			return nil
		}

		// 1. Strip out comment lines completely BEFORE splitting by semicolons
		var cleanLines []string
		for _, line := range strings.Split(schemaMatchReactionCounter, "\n") {
			trimmedLine := strings.TrimSpace(line)
			// Skip empty lines and lines that start with a comment hash
			if trimmedLine == "" || strings.HasPrefix(trimmedLine, "#") {
				continue
			}
			cleanLines = append(cleanLines, line)
		}
		
		// 2. Re-join the clean lines, then split by semicolon
		cleanSchema := strings.Join(cleanLines, "\n")
		statements := strings.Split(cleanSchema, ";")

		// 3. Execute the actual statements
		for _, stmt := range statements {
			stmt = strings.TrimSpace(stmt)
			if stmt == "" {
				continue
			}

			_, err = db.ExecContext(ctx, stmt)
			if err != nil {
				return fmt.Errorf("failed to execute SQL statement %q: %w", stmt, err)
			}
		}
	}
	log.Infof("CreateTable: table [%s] created", "match_reaction_counter")

	return nil
}

func (d *matchReactionCounterRepository) tableExists(ctx context.Context, db *sql.DB) (bool, error) {
	query := `
		SELECT 1
		FROM information_schema.tables 
		WHERE table_schema = DATABASE() 
		AND table_name = 'match_reaction_counters'
	`

	var exists bool
	err := db.QueryRowContext(ctx, query).Scan(&exists)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("failed to query table existence: %w", err)
	}

	return exists, nil
}




func (d *matchReactionCounterRepository) Create(ctx context.Context, entity *MatchReactionCounter) (*MatchReactionCounter, error) {
    if d.configProvider.BlockedWrites("match_reaction_counter") {
        return nil, ErrOperationBlocked
    }

	if entity.ID > 0 {
		return nil, fmt.Errorf("matchReactionCounterRepository.Create failed as ID > 0")
	}

	d.telemetryProvider.IncDALOperation("match_reaction_counter", "create")

	_, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.create(ctx, entity)
	})

	if err != nil {
		return nil, err
	}

	d.setCached(entity)

	// All lists cache should be flushed.
	d.FlushListCache()

	return entity, err
}

func (d *matchReactionCounterRepository) create(ctx context.Context, entity *MatchReactionCounter) (*MatchReactionCounter, error) {
	const operation = "create"
	start := time.Now()

	now := time.Now().Truncate(time.Second)
	
	// Only assign 'Created' if it hasn't been explicitly set by the domain layer
	if entity.Created.IsZero() {
		entity.Created = now
	}
	
	// 'Updated' should typically mirror 'Created' on initial insert
	if entity.Updated.IsZero() {
		entity.Updated = entity.Created
	}
	
	// Auto-generate UID fields if they are not provided

	query := `
		INSERT INTO match_reaction_counters (match_uid,reaction_count,
created,updated)
		VALUES (?,?,?,?)
	`

    db, dbErr := d.dbProvider.GetDatabase("matchReactionCounter", true);
    if dbErr != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)		
        return nil, dbErr
    }

	result, err := db.ExecContext(ctx, query,entity.MatchUid, entity.ReactionCount,
		entity.Created, entity.Updated)

	if err != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
		return nil, fmt.Errorf("failed to insert MatchReactionCounter: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
		return nil, fmt.Errorf("failed to get last insert ID: %w", err)
	}

	entity.ID = id	
	d.telemetryProvider.IncDBRequest("match_reaction_counter", operation)	
	d.telemetryProvider.ObserveDBLatency("match_reaction_counter", operation, time.Since(start).Seconds())	
	return entity, nil
}



func (d *matchReactionCounterRepository) CreateBulk(ctx context.Context, entities []*MatchReactionCounter) ([]*MatchReactionCounter, error) {
	if d.configProvider.BlockedWrites("match_reaction_counter") {
		return nil, ErrOperationBlocked
	}

	const operation = "create_bulk"
	d.telemetryProvider.IncDALOperation("match_reaction_counter", operation)

	result, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.createBulk(ctx, entities)
	})

	if err != nil {
		return nil, err
	}

	// All lists cache should be flushed.
	d.FlushListCache()

	return result.([]*MatchReactionCounter), err
}

func (d *matchReactionCounterRepository) createBulk(ctx context.Context, entities []*MatchReactionCounter) ([]*MatchReactionCounter, error) {
    const operation = "create_bulk"
    start := time.Now()

    if len(entities) == 0 {
        return nil, fmt.Errorf("empty entities list")
    }

    // Get the database connection once, outside the loop
    db, dbErr := d.dbProvider.GetDatabase("match_reaction_counter", true)
    if dbErr != nil {
        d.telemetryProvider.IncDBError("match_reaction_counter", operation)
        return nil, dbErr
    }

    now := time.Now().Truncate(time.Second)
    batchSize := 500 // Safe limit to prevent exceeding MySQL's max placeholders

    // Process entities in chunks
    for i := 0; i < len(entities); i += batchSize {
        end := i + batchSize
        if end > len(entities) {
            end = len(entities)
        }
        
        chunk := entities[i:end]

        // Prepare data and parameters scoped ONLY to this chunk
        valuePlaceholders := make([]string, 0, len(chunk))
        // Dynamically calculate fields per entity: custom columns + 2 (created, updated)
        params := make([]interface{}, 0, len(chunk)*(2 + 2)) 

        for _, entity := range chunk {
            if entity.ID > 0 {
                return nil, fmt.Errorf("entity with existing ID in bulk create")
            }

            // Preserve explicit timestamps or default to 'now'
            if entity.Created.IsZero() {
                entity.Created = now
            }
            if entity.Updated.IsZero() {
                entity.Updated = entity.Created
            }

			// Auto-generate UID fields if they are not provided

            valuePlaceholders = append(valuePlaceholders, "(?,?,?,?)")
            params = append(params,
                entity.MatchUid,
                entity.ReactionCount,
                entity.Created,
                entity.Updated,
            )
        }

        query := fmt.Sprintf(`
            INSERT INTO match_reaction_counters
            (match_uid,reaction_count,
created,updated)
            VALUES %s
        `, strings.Join(valuePlaceholders, ","))

        result, err := db.ExecContext(ctx, query, params...)
        if err != nil {
            d.telemetryProvider.IncDBError("match_reaction_counter", operation)
            return nil, fmt.Errorf("failed to bulk insert match_reaction_counters chunk: %w", err)
        }

        // Get generated IDs (works for MySQL/SQLite)
        lastID, err := result.LastInsertId()
        if err != nil {
            return nil, fmt.Errorf("failed to get last insert ID for chunk: %w", err)
        }

        rowsAffected, err := result.RowsAffected()
        if err != nil {
            return nil, fmt.Errorf("failed to get rows affected for chunk: %w", err)
        }

        if rowsAffected != int64(len(chunk)) {
            return nil, fmt.Errorf("mismatch between inserted rows and entity count in chunk")
        }

        // Assign generated IDs sequentially to the current chunk
        for j := range chunk {
            chunk[j].ID = lastID + int64(j)
			d.setCached(chunk[j])
        }
    }

    d.telemetryProvider.IncDBRequest("match_reaction_counter", operation) 
    d.telemetryProvider.ObserveDBLatency("match_reaction_counter", operation, time.Since(start).Seconds())    
    return entities, nil
}



// ErrNotFound is returned in case there was nothing to update; either missing id or newer version of entity is already stored.
func (d *matchReactionCounterRepository) Update(ctx context.Context, entity *MatchReactionCounter) error {
    if d.configProvider.BlockedWrites("match_reaction_counter") {
        return ErrOperationBlocked
    }

	const operation = "update"
	d.telemetryProvider.IncDALOperation("match_reaction_counter", operation)
	// 1. Get existing entity to check for changes. Required for proper cache invalidation.
	existing, err := d.GetByID(ctx, entity.ID)
	if err != nil {
		return fmt.Errorf("failed to get existing MatchReactionCounter, id: %v, err: %w", entity.ID, err)
	}

	
	var oldMatchUid string
	if existing.MatchUid != entity.MatchUid {
		oldMatchUid = existing.MatchUid
	}
		

	// Perform the update in DB.
	_, err2 := d.dbBreaker.Execute(func() (interface{}, error) {
		return nil, d.update(ctx, entity)
	})

	if err2 != nil {
		return err2
	}

	
	if oldMatchUid != "" {
		oldCacheKey := fmt.Sprintf("user_match_uid:%s", oldMatchUid)
		d.cache.Delete(oldCacheKey)
		d.cacheProvider.InvalidateCache("match_reaction_counter", oldCacheKey)
	}

	// Lets clear item from cache on other instances and here
	d.InvalidateCache(entity)
	d.FlushListCache()

	entity.Version++
	// our entity can become part of local cache
	d.setCached(entity)

	return nil
}

func (d *matchReactionCounterRepository) update(ctx context.Context, entity *MatchReactionCounter) error {
	const operation = "update"
	start := time.Now()

	entity.Updated = time.Now()

	query := `
		UPDATE match_reaction_counters
		SET match_uid = ?,reaction_count = ?, updated=?, version = version + 1
		WHERE id = ? AND version = ? 
	`

    db, dbErr := d.dbProvider.GetDatabase("matchReactionCounter", true);
    if dbErr != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
        return dbErr
    }

	res, err := db.ExecContext(ctx, query,entity.MatchUid, entity.ReactionCount,
	entity.Updated, entity.ID, entity.Version)

	if err != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
		return fmt.Errorf("failed to update MatchReactionCounter: %w", err)
	}

	rowsAffected, err := res.RowsAffected()
	if err != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
		return fmt.Errorf("failed to get rows affected: %w", err)
	}

	if rowsAffected == 0 {
		// clean out cache for specific ID to limit stale cache entries
		d.InvalidateCache(entity)
		return ErrNotFound
	}

	d.telemetryProvider.ObserveDBLatency("match_reaction_counter", operation, time.Since(start).Seconds())	

	return nil
}



func (d *matchReactionCounterRepository) Delete(ctx context.Context, entity *MatchReactionCounter) error {
    if d.configProvider.BlockedWrites("match_reaction_counter") {
        return ErrOperationBlocked
    }

	if entity.ID == 0 {
		// nothing can be deleted as entity is not created.
		return ErrNotFound
	}

	const operation = "delete"
	d.telemetryProvider.IncDALOperation("match_reaction_counter", operation)

	_, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return nil, d.delete(ctx, entity.ID)
	})

	if err != nil {
		return err
	}

	// Lets clear item from cache and on next use use DB as source of truth
	d.InvalidateCache(entity)
	d.FlushListCache()

	return err
}

func (d *matchReactionCounterRepository) delete(ctx context.Context, id int64) error {
	start := time.Now()
	const operation = "delete"

	
	query := `
		DELETE FROM match_reaction_counters
		WHERE id = ?
	`
	

    db, dbErr := d.dbProvider.GetDatabase("matchReactionCounter", true);
    if dbErr != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
        return dbErr
    }

	res, err := db.ExecContext(ctx, query, id)
	if err != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
		return fmt.Errorf("failed to delete match_reaction_counter: %w", err)
	}

	rowsAffected, err := res.RowsAffected()
	if err != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
		return fmt.Errorf("failed to get rows affected: %w", err)
	}

	if rowsAffected == 0 {
		return ErrNotFound
	}

	d.telemetryProvider.IncDBRequest("match_reaction_counter", operation)	
	d.telemetryProvider.ObserveDBLatency("match_reaction_counter", operation, time.Since(start).Seconds())	
	return nil
}






func (d *matchReactionCounterRepository) GetByID(ctx context.Context, id int64) (*MatchReactionCounter, error) {
    if d.configProvider.BlockedReads("match_reaction_counter") {
        return nil, ErrOperationBlocked
    }

    const operation = "get_by_id"
    d.telemetryProvider.IncDALOperation("match_reaction_counter", operation)

	// Load from cache
    cachedEntity, _ := d.getByIDCached(id)
    if cachedEntity != nil {
        return cachedEntity, nil
    }

	// Fallback to database if cache miss or decoding fails
	result, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.getByID(ctx, id)
	})

	if err != nil {
		return nil, err
	}

	entity, ok := result.(*MatchReactionCounter)
    if !ok {
        return nil, fmt.Errorf("invalid type")
    }

    _ = d.setCached(entity)

    return entity, err
}

func (d *matchReactionCounterRepository) setCached(entity *MatchReactionCounter) error {
    // if we have not reached the maximum number of items set the cache. otherwise expirations will
	// handle this
    itemCount := d.cache.ItemCount()
    if itemCount < 100000 {
        cacheKey := d.getCacheKey(entity.ID)

        // Store in cache with new format        
        d.telemetryProvider.IncCacheWrite("match_reaction_counter")
        d.telemetryProvider.SetCacheSize("match_reaction_counter", float64(itemCount+1))        

        copy := *entity
		d.cache.Set(cacheKey, &copy, time.Second*300)
    }

    return nil
}

// Gets entity from cache only or return nil
func (d *matchReactionCounterRepository) getByIDCached(id int64) (*MatchReactionCounter, error) {
    const operation = "get_by_id"
    cacheKey := d.getCacheKey(id)
    val, found := d.cache.Get(cacheKey)
    if found {
        entity, ok := val.(*MatchReactionCounter)
        if !ok {
            return nil, fmt.Errorf("matchReactionCounterRepository.GetById: Cache returned wrong type")
        }

        d.telemetryProvider.IncCacheHit("match_reaction_counter", operation)        
        copy := *entity
        return &copy, nil
    }

    // Cache missed or error during fetching cached data
    d.telemetryProvider.IncCacheMiss("match_reaction_counter", operation)        	

    return nil, nil
}

func (d *matchReactionCounterRepository) getByID(ctx context.Context, id int64) (*MatchReactionCounter, error) {
    const operation = "get_by_id"
    dbStart := time.Now();

    query := `
        SELECT id, version, match_uid, reaction_count, created, updated
        FROM match_reaction_counters
        WHERE id = ? 
    `

    db, dbErr := d.dbProvider.GetDatabase("matchReactionCounter", false);
    if dbErr != nil {
        d.telemetryProvider.IncDBError("match_reaction_counter", operation)
        return nil, dbErr
    }

    row := db.QueryRowContext(ctx, query, id)
    var entity MatchReactionCounter
    err := row.Scan(
        &entity.ID,
        &entity.Version,&entity.MatchUid,&entity.ReactionCount,
        &entity.Created,
        &entity.Updated,
        
    )
    if err != nil {
        if errors.Is(err, sql.ErrNoRows) {
            return nil, ErrNotFound
        }
        d.telemetryProvider.IncDBError("match_reaction_counter", operation)
        return nil, fmt.Errorf("failed to get MatchReactionCounter by ID: %w", err)
    }

    d.telemetryProvider.IncDBRequest("match_reaction_counter", operation)	
    d.telemetryProvider.ObserveDBLatency("match_reaction_counter", operation, time.Since(dbStart).Seconds())	
    return &entity, nil
}




func (d *matchReactionCounterRepository) GetByMatchUid(ctx context.Context, matchUid string) (*MatchReactionCounter, error) {
    if d.configProvider.BlockedReads("match_reaction_counter") {
        return nil, ErrOperationBlocked
    }

    const operation = "get_by_match_uid"
    d.telemetryProvider.IncDALOperation("match_reaction_counter", operation)

    // key would for example be: user_email:test@something.com, but in this case cache is only mapping email -> id
    cacheKey := fmt.Sprintf("match_reaction_counter_match_uid:%v", matchUid)

    // Fetch from cache MatchUid -> ID mapping
    val, found := d.cache.Get(cacheKey)
    if found {
        entityId, ok := val.(int64)
        if !ok {
            return nil, fmt.Errorf("matchReactionCounterRepository.GetByMatchUid: Cache returned wrong type; expected ID type")
        }

        d.telemetryProvider.IncCacheHit("match_reaction_counter", operation)        
        
        // return entity by that id
        return d.GetByID(ctx, entityId)
    }

    // Cache missed or error during fetching cached data
    d.telemetryProvider.IncCacheMiss("match_reaction_counter", operation)        	

	// Fallback to database if cache miss or decoding fails
	result, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.getByMatchUid(ctx, matchUid)
	})

	if err != nil {
		return nil, err
	}
	entity := result.(*MatchReactionCounter)

    // Warm up the primary entity cache
	d.setCached(entity)

	// Store in cache MatchUid -> ID mapping
    d.telemetryProvider.IncCacheWrite("match_reaction_counter")    
    d.cache.Set(cacheKey, entity.ID, time.Second*300)

    return entity, err
}

func (d *matchReactionCounterRepository) getByMatchUid(ctx context.Context, matchUid string) (*MatchReactionCounter, error) {
    const operation = "get_by_match_uid"
    dbStart := time.Now()

    query := `
        SELECT id, version, match_uid, reaction_count, created, updated
        FROM match_reaction_counters
        WHERE match_uid = ? 
    `

    db, dbErr := d.dbProvider.GetDatabase("matchReactionCounter", false);
    if dbErr != nil {
        d.telemetryProvider.IncDBError("match_reaction_counter", operation)
        return nil, dbErr
    }

    row := db.QueryRowContext(ctx, query, matchUid)
    var entity MatchReactionCounter
    err := row.Scan(
        &entity.ID,
        &entity.Version,
        &entity.MatchUid,
        &entity.ReactionCount,
        &entity.Created,
        &entity.Updated,
        
    )
    if err != nil {
        if errors.Is(err, sql.ErrNoRows) {
            return nil, ErrNotFound
        }

        d.telemetryProvider.IncDBError("match_reaction_counter", operation)
        return nil, fmt.Errorf("failed to get MatchReactionCounter by MatchUid: %w", err)
    }

    d.telemetryProvider.IncDBRequest("match_reaction_counter", operation)	
    d.telemetryProvider.ObserveDBLatency("match_reaction_counter", operation, time.Since(dbStart).Seconds())	
    return &entity, nil
}



func (d *matchReactionCounterRepository) GetByMatchUids(ctx context.Context, matchUids []string) ([]*MatchReactionCounter, error) {
    if d.configProvider.BlockedReads("match_reaction_counter") {
        return nil, ErrOperationBlocked
    }

    if len(matchUids) == 0 {
        return nil, nil // Nothing to fetch
    }
    
    // Hard limit to prevent massive memory allocations and driver crashes
    if len(matchUids) > 5000 {
        return nil, fmt.Errorf("bulk get operation exceeds maximum limit of 5000 items")
    }

    const operation = "get_bulk_by_match_uid"
    d.telemetryProvider.IncDALOperation("match_reaction_counter", operation)

    var results []*MatchReactionCounter
    var missingKeys []interface{}

    // 1. Check local in-memory cache for each key
    for _, key := range matchUids {
        cacheKey := fmt.Sprintf("match_reaction_counter_match_uid:%v", key)
        val, found := d.cache.Get(cacheKey)
        if found {
            entityId, ok := val.(int64)
            if ok {
                entity, _ := d.getByIDCached(entityId)
                if entity != nil {
                    results = append(results, entity)
                    continue
                }
            }
        }
        missingKeys = append(missingKeys, key)
    }

    if len(missingKeys) == 0 {
        d.telemetryProvider.IncCacheHit("match_reaction_counter", operation)
        return results, nil
    }

    d.telemetryProvider.IncCacheMiss("match_reaction_counter", operation)

    // 2. Fetch cache misses from DB via Circuit Breaker in safe chunks
    var dbEntities []*MatchReactionCounter
    batchSize := 500
    
    for i := 0; i < len(missingKeys); i += batchSize {
        end := i + batchSize
        if end > len(missingKeys) {
            end = len(missingKeys)
        }
        chunk := missingKeys[i:end]

        dbResult, err := d.dbBreaker.Execute(func() (interface{}, error) {
            return d.getByMatchUids(ctx, chunk)
        })

        if err != nil {
            return nil, err // Fail fast if a chunk fails
        }
        
        dbEntities = append(dbEntities, dbResult.([]*MatchReactionCounter)...)
    }

    results = append(results, dbEntities...)

    // 3. Cache the newly fetched items for future zero-latency access
    for _, entity := range dbEntities {
        d.setCached(entity)
        cacheMappingKey := fmt.Sprintf("match_reaction_counter_match_uid:%v", entity.MatchUid)
        d.cache.Set(cacheMappingKey, entity.ID, time.Second*300)
    }

    return results, nil
}

func (d *matchReactionCounterRepository) getByMatchUids(ctx context.Context, missingKeys []interface{}) ([]*MatchReactionCounter, error) {
    const operation = "get_bulk_by_match_uid"
    dbStart := time.Now()

    // Dynamically build ?,?,? placeholders for the IN clause
    placeholders := make([]string, len(missingKeys))
    for i := range missingKeys {
        placeholders[i] = "?"
    }

    query := fmt.Sprintf(`
        SELECT id, version, match_uid, reaction_count, created, updated
        FROM match_reaction_counters
        WHERE match_uid IN (%s) 
    `, strings.Join(placeholders, ","))

    db, dbErr := d.dbProvider.GetDatabase("matchReactionCounter", false)
    if dbErr != nil {
        d.telemetryProvider.IncDBError("match_reaction_counter", operation)
        return nil, dbErr
    }

    rows, err := db.QueryContext(ctx, query, missingKeys...)
    if err != nil {
        d.telemetryProvider.IncDBError("match_reaction_counter", operation)
        return nil, fmt.Errorf("failed to bulk query match_reaction_counters: %w", err)
    }
    defer rows.Close()

    var entities []*MatchReactionCounter
    for rows.Next() {
        var entity MatchReactionCounter
        err := rows.Scan(
            &entity.ID,
            &entity.Version,
            &entity.MatchUid,
            &entity.ReactionCount,
            &entity.Created,
            &entity.Updated,
            
        )
        if err != nil {
            d.telemetryProvider.IncDBError("match_reaction_counter", operation)
            return nil, fmt.Errorf("failed to scan MatchReactionCounter: %w", err)
        }
        entities = append(entities, &entity)
    }

    d.telemetryProvider.IncDBRequest("match_reaction_counter", operation)
    d.telemetryProvider.ObserveDBLatency("match_reaction_counter", operation, time.Since(dbStart).Seconds())

    return entities, nil
}



// UpsertReactionCounts executes a bulk upsert (INSERT ... ON DUPLICATE KEY UPDATE).
//
// CACHING NOTE:
// This operation modifies records in bulk. To safely maintain cache integrity,
// it triggers a global FlushAllCache() if any rows are affected.
func (d *matchReactionCounterRepository) UpsertReactionCounts(ctx context.Context, entities []*MatchReactionCounter) error {
	if d.configProvider.BlockedWrites("match_reaction_counter") {
		return ErrOperationBlocked
	}

	if len(entities) == 0 {
		return nil
	}

	// Hard limit to prevent massive memory allocations and driver crashes
	if len(entities) > 5000 {
		return fmt.Errorf("bulk upsert operation exceeds maximum limit of 5000 items")
	}

	const operation = "upsert_bulk_upsert_reaction_counts"
	d.telemetryProvider.IncDALOperation("match_reaction_counter", operation)

	result, err := d.dbBreaker.Execute(func() (interface{}, error) {
		return d.upsertReactionCounts(ctx, entities)
	})

	if err != nil {
		return err
	}

	rowsAffected := result.(int64)
	if rowsAffected > 0 {
		d.FlushAllCache()
	}

	return nil
}

func (d *matchReactionCounterRepository) upsertReactionCounts(ctx context.Context, entities []*MatchReactionCounter) (int64, error) {
	const operation = "upsert_bulk_upsert_reaction_counts"
	start := time.Now()
	now := time.Now().Truncate(time.Second)

	db, dbErr := d.dbProvider.GetDatabase("match_reaction_counter", true)
	if dbErr != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
		return 0, dbErr
	}
    
    if db == nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", operation)
		return 0, errors.New("database connection is nil")
	}

	var totalRowsAffected int64
	batchSize := 500

	for i := 0; i < len(entities); i += batchSize {
		end := i + batchSize
		if end > len(entities) {
			end = len(entities)
		}
		chunk := entities[i:end]

		valuePlaceholders := make([]string, 0, len(chunk))
		// Dynamically calculate fields per entity: custom columns + 2 (created, updated)
		params := make([]interface{}, 0, len(chunk)*(2 + 2))

		for _, entity := range chunk {
			if entity.Created.IsZero() {
				entity.Created = now
			}
			if entity.Updated.IsZero() {
				entity.Updated = entity.Created
			}

			valuePlaceholders = append(valuePlaceholders, "(?,?,?,?)")
			params = append(params,
				entity.MatchUid,
				entity.ReactionCount,
				entity.Created,
				entity.Updated,
			)
		}

		query := fmt.Sprintf(`
			INSERT INTO match_reaction_counters
			(match_uid,reaction_count,
created,updated)
			VALUES %s
			ON DUPLICATE KEY UPDATE
				reaction_count = match_reaction_counters.reaction_count + VALUES(reaction_count),
			updated = VALUES(updated),
			version = match_reaction_counters.version + 1
		`, strings.Join(valuePlaceholders, ","))

		res, err := db.ExecContext(ctx, query, params...)
		if err != nil {
			d.telemetryProvider.IncDBError("match_reaction_counter", operation)
			return 0, fmt.Errorf("failed to bulk upsert match_reaction_counters chunk: %w", err)
		}

		rowsAffected, err := res.RowsAffected()
		if err == nil {
			totalRowsAffected += rowsAffected
		}
	}

	d.telemetryProvider.IncDBRequest("match_reaction_counter", operation)
	d.telemetryProvider.ObserveDBLatency("match_reaction_counter", operation, time.Since(start).Seconds())
	
	return totalRowsAffected, nil
}










// IncrementReaction executes an O(1) in-memory increment to be flushed later.
func (d *matchReactionCounterRepository) IncrementReaction(ctx context.Context, matchUid string, delta int) error {
	bufferKey := "purplehoney:match_reaction_counter:reaction_count:buffer"
	
	if err := d.cacheProvider.HIncrBy(ctx, bufferKey, matchUid, int64(delta)); err != nil {
		d.telemetryProvider.IncDBError("match_reaction_counter", "increment_reaction_count_buffer")
		return err
	}
	return nil
}