/*
NOTE! This code is autogenerated.
Don't manually change this code.
Version [2d383a8928edcc845ed2c7cef958bb94d591275835271bc6bc36581571cb98e6]
*/
package dal

import (
	"context"
	"encoding/gob"
	"time"
	
)

func init() {
	gob.Register(MatchReactionCounter{})
}


// Struct representing MatchReactionCounter. Do not use these structs directly across services as this struct carries db specific information.
// recommendation: create higher level service layer structs that might look same or very similar instead.
type MatchReactionCounter struct {
    ID        int64 `json:"id"` // Auto-incremented number
    Version   int32 `json:"version"` // Only change this value directly in very specific cases.  
    
    MatchUid string `json:"match_uid"`
    ReactionCount int32 `json:"reaction_count"`

    Created   time.Time `json:"created"`
    Updated   time.Time `json:"updated"`

}


// MatchReactionCounterRepository defines the interface for the MatchReactionCounter.
// Use this interface in your services to easily mock the database.
type MatchReactionCounterRepository interface {
    CreateTable(ctx context.Context) error
    GetByID(ctx context.Context, id int64) (*MatchReactionCounter, error)

    InvalidateCache(entity *MatchReactionCounter)
    FlushListCache()
    FlushAllCache()
    Create(ctx context.Context, entity *MatchReactionCounter) (*MatchReactionCounter, error)
    
    // CreateBulk performs a batch insert of multiple MatchReactionCounter entities.
    //
    // CACHING & PERFORMANCE NOTE:
    // This operation safely batches inserts into chunks of 500 to avoid exceeding the 
    // database driver's maximum placeholder limits.
    // 
    // Because new items are being added to the database, this function will automatically 
    // call FlushListCache() to ensure that any cached paginated lists or count queries 
    // are invalidated and recalculated on their next request.
    CreateBulk(ctx context.Context, entities []*MatchReactionCounter) ([]*MatchReactionCounter, error)
    
    Update(ctx context.Context, entity *MatchReactionCounter) error
    Delete(ctx context.Context, entity *MatchReactionCounter) error
    GetByMatchUid(ctx context.Context, matchUid string) (*MatchReactionCounter, error)
    // GetByMatchUids executes a bulk get operation.
    //
    // PERFORMANCE & CACHING NOTE:
    // This function is highly optimized for caching. It first checks the local in-memory 
    // cache for every individual key. Only the missing keys (cache misses) are fetched 
    // from the database in safe chunks of 500. The newly fetched items are then cached 
    // automatically.
    //
    // To prevent massive memory allocations and driver crashes, this operation is 
    // hard-limited to 5000 items per call.
    GetByMatchUids(ctx context.Context, matchUids []string) ([]*MatchReactionCounter, error)
	// UpsertReactionCounts executes an INSERT ... ON DUPLICATE KEY UPDATE in batches.
     // ⚠️ CAUTION - CACHE FLUSH NOTE ⚠️
    // Because bulk updates modify multiple records simultaneously, it is difficult to 
    // track and selectively invalidate individual cache entries safely. Therefore, if 
    // this operation successfully updates one or more rows, it will trigger a global 
    // FlushAllCache() to ensure local memory safety and broadcast cache invalidation 
    // to peer nodes via Pub/Sub. Use this operation carefully in high-read environments.
    //
    // This operation is hard-limited to 5000 items and executes in database batches of 500.
	UpsertReactionCounts(ctx context.Context, entities []*MatchReactionCounter) error
	// IncrementReaction executes an O(1) in-memory increment to be flushed later.
	IncrementReaction(ctx context.Context, matchUid string, delta int) error
}

