/*
NOTE! This code is autogenerated by dalforge.
Version [451fbde50057770bf5820107beeca0955a312969a0581e591c491e5d70e629bb]
DO NOT EDIT MANUALLY.
*/
package dal

import (
	"context"
	"strconv"
	"sync"
	"time"

	log "github.com/sirupsen/logrus"
)


type IncrementReactionFlusher struct {
	repo          MatchReactionCounterRepository
	cacheProvider CacheProvider
	telemetry     TelemetryProvider
	interval      time.Duration
	stopChan      chan struct{}
	wg            sync.WaitGroup // Enables graceful shutdown
}

func NewIncrementReactionFlusher(repo MatchReactionCounterRepository, cacheProvider CacheProvider, telemetry TelemetryProvider) *IncrementReactionFlusher {
	return &IncrementReactionFlusher{
		repo:          repo,
		cacheProvider: cacheProvider,
		telemetry:     telemetry,
		interval:      time.Duration(300) * time.Second,
		stopChan:      make(chan struct{}),
	}
}

func (f *IncrementReactionFlusher) Start(parentCtx context.Context) {
	ticker := time.NewTicker(f.interval)
	go func() {
		for {
			select {
			case <-parentCtx.Done():
				ticker.Stop()
				return
			case <-f.stopChan:
				ticker.Stop()
				return
			case <-ticker.C:
				f.wg.Add(1)
				// ARCHITECTURE: Create a bounded context that expires slightly before the next tick.
				// This guarantees the worker never permanently deadlocks if MySQL hangs.
				timeoutDuration := f.interval - (5 * time.Second)
				if timeoutDuration <= 0 {
					timeoutDuration = f.interval
				}
				ctx, cancel := context.WithTimeout(parentCtx, timeoutDuration)
				
				f.flush(ctx)
				
				cancel()
				f.wg.Done()
			}
		}
	}()
}

func (f *IncrementReactionFlusher) Stop() {
	close(f.stopChan)
}

// Wait blocks until the current flush operation completely finishes.
// Call this during application shutdown (SIGTERM) to prevent data corruption.
func (f *IncrementReactionFlusher) Wait() {
	f.wg.Wait()
}

func (f *IncrementReactionFlusher) flush(ctx context.Context) {
	lockKey := "purplehoney:match_reaction_counter:reaction_count:flush_lock"
	
	// ARCHITECTURE: Dynamically bind the lock TTL to the tick interval.
	// This prevents concurrent pod executions even during heavy processing.
	acquired, err := f.cacheProvider.SetNX(ctx, lockKey, "locked", f.interval)
	if err != nil || !acquired {
		return // Another instance is currently flushing
	}
	defer f.cacheProvider.Del(context.Background(), lockKey) // Use background context to guarantee lock release

	bufferKey := "purplehoney:match_reaction_counter:reaction_count:buffer"
	processingKey := bufferKey + ":processing"

	// 2. Attempt to drain any leftover processing key from a previous failed run
	leftoverFailed := f.drain(ctx, processingKey)
	if leftoverFailed {
		log.Warnf("Previous flush failed and could not be recovered. Skipping this tick to prevent overwriting: %s", bufferKey)
		return
	}

	// 3. Rename buffer to isolate current snapshot from incoming writes
	err = f.cacheProvider.Rename(ctx, bufferKey, processingKey)
	if err != nil {
		return // Empty buffer, nothing to rename
	}

	// 4. Drain the newly renamed processing key
	f.drain(ctx, processingKey)
}

// drain iterates through the Redis hash and pushes data to MySQL.
// Returns true if a critical failure occurred, preventing full deletion of the processing key.
func (f *IncrementReactionFlusher) drain(ctx context.Context, processingKey string) bool {
	var cursor uint64
	var batch []*MatchReactionCounter
	const maxBatchSize = 5000
	hasErrors := false

	for {
		// Respect context cancellation mid-iteration
		select {
		case <-ctx.Done():
			log.Warnf("Context cancelled during flush of %s", processingKey)
			return true 
		default:
		}

		var results []string
		var err error
		results, cursor, err = f.cacheProvider.HScan(ctx, processingKey, cursor, "*", 1000)
		if err != nil {
			log.Errorf("Failed to HSCAN processing key %s: %v", processingKey, err)
			return true
		}

		if len(results) == 0 && cursor == 0 {
			break
		}

		for i := 0; i < len(results); i += 2 {
			identifier := results[i]
			countStr := results[i+1]
			count, _ := strconv.ParseInt(countStr, 10, 32)
			
			entity := &MatchReactionCounter{
				MatchUid: identifier,
			}
			entity.ReactionCount = int32(count)
			
			batch = append(batch, entity)
		}

		// Chunk database upserts to bound memory allocation
		if len(batch) >= maxBatchSize {
			if !f.upsertBatch(ctx, batch, processingKey) {
				hasErrors = true
			}
			batch = batch[:0] // Clear the slice while retaining capacity
		}

		if cursor == 0 {
			break
		}
	}

	// Flush any remaining records in the batch
	if len(batch) > 0 {
		if !f.upsertBatch(ctx, batch, processingKey) {
			hasErrors = true
		}
	}

	// Only delete the processing key if ALL chunks succeeded
	if !hasErrors {
		f.cacheProvider.Del(ctx, processingKey)
		return false
	}

	return true
}

func (f *IncrementReactionFlusher) upsertBatch(ctx context.Context, batch []*MatchReactionCounter, processingKey string) bool {
	err := f.repo.UpsertReactionCounts(ctx, batch)
	if err != nil {
		log.Errorf("Failed to bulk upsert flushed buffer %s: %v", processingKey, err)
		return false
	}
	return true
}
