/*
NOTE! This code is autogenerated.
Don't manually change this code.
Version [7204d888b7665efb7f5678fa932e34bb097f32126481080197ea6ca1889268ac]
*/
package dal

import (
	"context"
	"encoding/gob"
	"time"
	
)

func init() {
	gob.Register(Post{})
}


// Struct representing Post. Do not use these structs directly across services as this struct carries db specific information.
// recommendation: create higher level service layer structs that might look same or very similar instead.
type Post struct {
    ID        int64 `json:"id"` // Auto-incremented number
    Version   int32 `json:"version"` // Only change this value directly in very specific cases.  
    
    Deleted bool `json:"deleted"`
    ExpiresAt time.Time `json:"expires_at"`
    LanguageId string `json:"language_id"`
    Post string `json:"post"`
    Revoked bool `json:"revoked"`
    StoryUid string `json:"story_uid"`
    TargetAge int8 `json:"target_age"`
    UserId string `json:"user_id"`

    Created   time.Time `json:"created"`
    Updated   time.Time `json:"updated"`

}


// PostRepository defines the interface for the Post.
// Use this interface in your services to easily mock the database.
type PostRepository interface {
    CreateTable(ctx context.Context) error
    GetByID(ctx context.Context, id int64) (*Post, error)

    InvalidateCache(entity *Post)
    FlushListCache()
    FlushAllCache()
    Create(ctx context.Context, entity *Post) (*Post, error)
    
    // CreateBulk performs a batch insert of multiple Post entities.
    //
    // CACHING & PERFORMANCE NOTE:
    // This operation safely batches inserts into chunks of 500 to avoid exceeding the 
    // database driver's maximum placeholder limits.
    // 
    // Because new items are being added to the database, this function will automatically 
    // call FlushListCache() to ensure that any cached paginated lists or count queries 
    // are invalidated and recalculated on their next request.
    CreateBulk(ctx context.Context, entities []*Post) ([]*Post, error)
    
    Update(ctx context.Context, entity *Post) error
    Delete(ctx context.Context, entity *Post) error
    // ListByLanguages executes a bulk list operation using an IN clause on the language_id column.
    //
    // PERFORMANCE & CACHING NOTE:
    // To prevent massive memory allocations and database driver crashes, this operation 
    // is hard-limited to 5000 items and executes database queries in safe batches of 500.
    // 
    // Unlike standard list operations, this function does NOT use the listCache because 
    // the permutations of dynamic input slices are practically infinite. Instead, it queries the 
    // database directly but aggressively warms the local single-item cache with the 
    // results. Subsequent fetches for any individual Post returned by this query 
    // will be instant zero-latency cache hits.
    ListByLanguages(ctx context.Context, languageIds []string) ([]*Post, error)
    // ListByUserAndStories executes a bulk list operation using an IN clause on the story_uid column.
    // It also applies the following custom filter: user_id = :user
    //
    // PERFORMANCE & CACHING NOTE:
    // To prevent massive memory allocations and database driver crashes, this operation 
    // is hard-limited to 5000 items and executes database queries in safe batches of 500.
    // 
    // Unlike standard list operations, this function does NOT use the listCache because 
    // the permutations of dynamic input slices are practically infinite. Instead, it queries the 
    // database directly but aggressively warms the local single-item cache with the 
    // results. Subsequent fetches for any individual Post returned by this query 
    // will be instant zero-latency cache hits.
    ListByUserAndStories(ctx context.Context, user string, storyUids []string) ([]*Post, error)
    // GetStoryUidsByUser fetches a list of story_uid values.
    // CACHING NOTE: Uses the shared listCache for invalidation.
    GetStoryUidsByUser(ctx context.Context, userId string) ([]string, error)
    ListById(ctx context.Context, startID int64, pageSize int) ([]*Post, error)
    CountListById(ctx context.Context, ) (int64, error)
    RecentPosts(ctx context.Context, targetAge int8, startID int64, pageSize int) ([]*Post, error)
    CountRecentPosts(ctx context.Context, targetAge int8) (int64, error)
    // DeleteExpired executes a custom bulk delete operation.
    // 
    // ⚠️ CAUTION - CACHE FLUSH NOTE ⚠️
    // Because bulk deletions modify multiple records simultaneously, it is difficult to 
    // track and selectively invalidate individual cache entries safely. Therefore, if 
    // this operation successfully deletes one or more rows, it will trigger a global 
    // FlushAllCache() to ensure local memory safety and broadcast cache invalidation 
    // to peer nodes via Pub/Sub. Use this operation carefully in high-read environments.
    //
    // PERFORMANCE NOTE: To prevent database locks, undo-log bloat, and replication lag, 
    // this operation requires a limit parameter. If the provided limit is <= 0 or > 5000, 
    // it will be automatically clamped to 5000.
    DeleteExpired(ctx context.Context, cutoff time.Time, limit int) (int64, error)

}
