/*
NOTE! This code is autogenerated.
Don't manually change this code.
Version [7204d888b7665efb7f5678fa932e34bb097f32126481080197ea6ca1889268ac]
*/
package dal

import (
	"context"
	"encoding/gob"
	"time"
	
	"encoding/json"
	
)

func init() {
	gob.Register(User{})
}


// Struct representing User. Do not use these structs directly across services as this struct carries db specific information.
// recommendation: create higher level service layer structs that might look same or very similar instead.
type User struct {
    ID        int64 `json:"id"` // Auto-incremented number
    Version   int32 `json:"version"` // Only change this value directly in very specific cases.  
    
    Age int8 `json:"age"`
    Birthdate *time.Time `json:"birthdate"`
    Email string `json:"email"`
    Meta *json.RawMessage `json:"meta"`
    Status *string `json:"status"`
    Uid string `json:"uid"`

    Created   time.Time `json:"created"`
    Updated   time.Time `json:"updated"`

    DeletedAt *time.Time `json:"deleted_at"`

}


// UserRepository defines the interface for the User.
// Use this interface in your services to easily mock the database.
type UserRepository interface {
    CreateTable(ctx context.Context) error
    GetByID(ctx context.Context, id int64) (*User, error)

    InvalidateCache(entity *User)
    FlushListCache()
    FlushAllCache()
    Create(ctx context.Context, entity *User) (*User, error)
    
    // CreateBulk performs a batch insert of multiple User entities.
    //
    // CACHING & PERFORMANCE NOTE:
    // This operation safely batches inserts into chunks of 500 to avoid exceeding the 
    // database driver's maximum placeholder limits.
    // 
    // Because new items are being added to the database, this function will automatically 
    // call FlushListCache() to ensure that any cached paginated lists or count queries 
    // are invalidated and recalculated on their next request.
    CreateBulk(ctx context.Context, entities []*User) ([]*User, error)
    
    Update(ctx context.Context, entity *User) error
    Delete(ctx context.Context, entity *User) error
    HardDelete(ctx context.Context, entity *User) error
    GetByEmail(ctx context.Context, email string) (*User, error)
    GetByUid(ctx context.Context, uid string) (*User, error)
    // GetByUids executes a bulk get operation.
    //
    // PERFORMANCE & CACHING NOTE:
    // This function is highly optimized for caching. It first checks the local in-memory 
    // cache for every individual key. Only the missing keys (cache misses) are fetched 
    // from the database in safe chunks of 500. The newly fetched items are then cached 
    // automatically.
    //
    // To prevent massive memory allocations and driver crashes, this operation is 
    // hard-limited to 5000 items per call.
    GetByUids(ctx context.Context, uids []string) ([]*User, error)
    // GetByIds executes a bulk get operation.
    //
    // PERFORMANCE & CACHING NOTE:
    // This function is highly optimized for caching. It first checks the local in-memory 
    // cache for every individual key. Only the missing keys (cache misses) are fetched 
    // from the database in safe chunks of 500. The newly fetched items are then cached 
    // automatically.
    //
    // To prevent massive memory allocations and driver crashes, this operation is 
    // hard-limited to 5000 items per call.
    GetByIds(ctx context.Context, ids []int64) ([]*User, error)
    // UpdateStatusByUids executes a bulk partial update using an IN clause.
    //
    // ⚠️ CAUTION - CACHE FLUSH NOTE ⚠️
    // Because bulk updates modify multiple records simultaneously, it is difficult to 
    // track and selectively invalidate individual cache entries safely. Therefore, if 
    // this operation successfully updates one or more rows, it will trigger a global 
    // FlushAllCache() to ensure local memory safety and broadcast cache invalidation 
    // to peer nodes via Pub/Sub. Use this operation carefully in high-read environments.
    //
    // This operation is hard-limited to 5000 items and executes in database batches of 500.
    UpdateStatusByUids(ctx context.Context, status *string, uids []string) error
    // UpdateAgeByIds executes a bulk partial update using an IN clause.
    //
    // ⚠️ CAUTION - CACHE FLUSH NOTE ⚠️
    // Because bulk updates modify multiple records simultaneously, it is difficult to 
    // track and selectively invalidate individual cache entries safely. Therefore, if 
    // this operation successfully updates one or more rows, it will trigger a global 
    // FlushAllCache() to ensure local memory safety and broadcast cache invalidation 
    // to peer nodes via Pub/Sub. Use this operation carefully in high-read environments.
    //
    // This operation is hard-limited to 5000 items and executes in database batches of 500.
    UpdateAgeByIds(ctx context.Context, age int8, ids []int64) error
    ListById(ctx context.Context, startID int64, pageSize int) ([]*User, error)
    CountListById(ctx context.Context, ) (int64, error)
    ListByBday(ctx context.Context, birthdate *time.Time, startID int64, pageSize int) ([]*User, error)
    CountListByBday(ctx context.Context, birthdate *time.Time) (int64, error)
    ListByAge(ctx context.Context, minage int8, startID int64, pageSize int) ([]*User, error)
    CountListByAge(ctx context.Context, minage int8) (int64, error)
    ListByStatus(ctx context.Context, status *string, startID int64, pageSize int) ([]*User, error)
    CountListByStatus(ctx context.Context, status *string) (int64, error)
    // DeleteOlder executes a custom bulk delete operation.
    // 
    // ⚠️ CAUTION - CACHE FLUSH NOTE ⚠️
    // Because bulk deletions modify multiple records simultaneously, it is difficult to 
    // track and selectively invalidate individual cache entries safely. Therefore, if 
    // this operation successfully deletes one or more rows, it will trigger a global 
    // FlushAllCache() to ensure local memory safety and broadcast cache invalidation 
    // to peer nodes via Pub/Sub. Use this operation carefully in high-read environments.
    //
    // PERFORMANCE NOTE: To prevent database locks, undo-log bloat, and replication lag, 
    // this operation requires a limit parameter. If the provided limit is <= 0 or > 5000, 
    // it will be automatically clamped to 5000.
    DeleteOlder(ctx context.Context, age int8, limit int) (int64, error)
    
    // HardDeleteOlder executes a permanent custom bulk delete operation.
    // 
    // ⚠️ CAUTION - CACHE FLUSH NOTE ⚠️
    // Because bulk deletions modify multiple records simultaneously, it is difficult to 
    // track and selectively invalidate individual cache entries safely. Therefore, if 
    // this operation successfully deletes one or more rows, it will trigger a global 
    // FlushAllCache() to ensure local memory safety and broadcast cache invalidation 
    // to peer nodes via Pub/Sub. Use this operation carefully in high-read environments.
    //
    // PERFORMANCE NOTE: To prevent database locks, undo-log bloat, and replication lag, 
    // this operation requires a limit parameter. If the provided limit is <= 0 or > 5000, 
    // it will be automatically clamped to 5000.
    HardDeleteOlder(ctx context.Context, age int8, limit int) (int64, error)

}
